/// Routes that map to [ComingSoonView] until fully implemented.
class ComingSoonRoutes {
  ComingSoonRoutes._();

  static const entries = <String, String>{
    '/notifications': 'Notifications',
    '/location': 'Location',
    '/allrestaurants': 'All Restaurants',
    '/categoryresults': 'Category Results',
    '/filtersort': 'Filter & Sort',
    '/itemdetail': 'Item Detail',
    '/restaurantclosed': 'Restaurant Closed',
    '/scheduledorder': 'Scheduled Order',
    '/grouporder': 'Group Order',
    '/emptycart': 'Empty Cart',
    '/checkoutsummary': 'Checkout Summary',
    '/payment': 'Payment',
    '/orderconfirmation': 'Order Confirmed',
    '/tracking': 'Order Tracking',
    '/activeorders': 'Active Orders',
    '/cancelorder': 'Cancel Order',
    '/reorderconfirm': 'Reorder Confirm',
    '/invoice': 'Invoice',
    '/coupondetail': 'Coupon Details',
    '/promo': 'Promo',
    '/flashsale': 'Flash Sale',
    '/offers': 'Offers & Coupons',
    '/selecttable': 'Select Table',
    '/bookingconfirm': 'Booking Confirmed',
    '/bookinghistory': 'Booking History',
    '/favourites': 'Favourites',
    '/changephone': 'Change Phone',
    '/notificationsettings': 'Notification Settings',
    '/privacy': 'Privacy',
    '/language': 'Language',
    '/referral': 'Refer & Earn',
    '/rewards': 'Rewards',
    '/feedback': 'Feedback',
    '/blockedusers': 'Blocked Users',
    '/deleteaccount': 'Delete Account',
    '/refundstatus': 'Refund Status',
    '/livechat': 'Live Chat',
    '/safety': 'Safety',
    '/about': 'About FooDeeZ',
    '/dispute': 'Dispute',
    '/searchdishes': 'Search Dishes',
    '/nointernet': 'No Internet',
    '/appupdate': 'App Update',
    '/servererror': 'Server Error',
    '/sessionexpired': 'Session Expired',
    '/maintenance': 'Maintenance',
    '/welcomeback': 'Welcome Back',
    '/onboarding': 'Onboarding',
    '/settings': 'Settings',
    '/profile/settings': 'Settings',
  };
}
